### ISSUE TITLE
Amplify CLI hangs for hours when creating API models

### ISSUE THREAD

**Issue by kannieWeesNie** [aws-amplify/amplify-android#895]
I have a test Android app using Amplify Auth. Everything works as expected.

I then tried updating the Auth category to add user pool groups and an admin
queries api. When running push, the build hangs at "Creating API models..." so
I closed Android Studio and tried again with the same result.

I then removed Auth (and user pool groups, the lambda function and api) and
added Auth again using the CLI (`amplify add auth`).

Here are the options I selected for the API:

```console
Do you want to add User Pool Groups? Yes
? Provide a name for your user pool group: admin
? Do you want to add another User Pool Group Yes
? Provide a name for your user pool group: users
? Do you want to add another User Pool Group No
√ Sort the user pool groups in order of preference · admin, users
 Do you want to add an admin queries API? Yes
? Do you want to restrict access to the admin queries API to a specific Group Yes
? Select the group to restrict access with: admin
```

When running push, it again hangs at:

```console
Creating API models...
/ Updating resources in the cloud. This may take a few minutes...
```

After more than 2 hours, I closed Android Studio.

Appreciate any help in solving this problem. Thanks.

**Comment by jpignata** [comment]
Are you using the gradle integration to run modelgen? Or running the CLI within a terminal?

**Comment by jamesonwilliams** [comment]
Is this a duplicate of https://github.com/aws-amplify/amplify-cli/issues/5557? I also noticed this [same question on StackOverflow](https://stackoverflow.com/questions/64319037/amplify-cli-hangs-for-hours-when-creating-api-models).

**Comment by yuth** [comment]
https://github.com/aws-amplify/amplify-cli/pull/5564 should fix this error

**Comment by kannieWeesNie** [comment]
@jpignata > Are you using the gradle integration to run modelgen? Or running the CLI within a terminal?

i am using the CLI within a terminal

**Comment by kannieWeesNie** [comment]
@jamesonwilliams  > Is this a duplicate of [aws-amplify/amplify-cli#5557](https://github.com/aws-amplify/amplify-cli/issues/5557)? I also noticed this [same question on StackOverflow](https://stackoverflow.com/questions/64319037/amplify-cli-hangs-for-hours-when-creating-api-models).

i am not sure if it is a duplicate? that issue refers to the REST api category whereas my issue refers to the auth category and occurs when including "Do you want to add an admin queries API?" when creating or updating the auth category.

see docs for Admin Action [https://docs.amplify.aws/cli/auth/admin](url). i.e my issue

**Comment by kannieWeesNie** [comment]
@yuth > [aws-amplify/amplify-cli#5564](https://github.com/aws-amplify/amplify-cli/pull/5564) should fix this error

thanks for help but unfortunately it has not resolved my issue. it still hangs with this message....Creating API models...
\ Updating resources in the cloud. This may take a few minutes...

to be clear, i am referring to adding the AUTHENTICATION Admin actions, enabling admin queries in the auth category

i add the admin queries api while selecting the options when adding the auth category in android studio terminal. please see attached file for all the steps i took, which options i selected, etc.


[amplify_add_auth_api.txt](https://github.com/aws-amplify/amplify-android/files/5370414/amplify_add_auth_api.txt)

**Comment by jpignata** [comment]
Thanks. Seems like we should move this to the CLI repo for that team to weigh in. I'll continue to monitor.

**Comment by richardmcclellan** [comment]
There's already an issue 

> @yuth > [aws-amplify/amplify-cli#5564](https://github.com/aws-amplify/amplify-cli/pull/5564) should fix this error
> 
> thanks for help but unfortunately it has not resolved my issue. 

Hi @kannieWeesNie, per https://github.com/aws-amplify/amplify-cli/issues/5557 this issue was resolved in v4.29.7 of the CLI, which was just released about an hour ago.   Can you update to the latest version (`npm i -g @aws-amplify/cli`) and try again?
